name: AI Code Reviewer

on:
  pull_request:
    types:
      - opened
      - synchronize

permissions:
  contents: write

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: AI Code Reviewer
        uses: aidar-freeed/ai-codereviewer@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_API_MODEL: "gpt-3.5-turbo" # Optional: Standard ist "gpt-4"
          exclude: "**/*.json, **/*.md" # Optional: Zu ignorierende Dateimuster
